# Generated by Django 3.1.7 on 2021-04-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(max_length=2000)),
                ('short_path_component', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_path_component'], name='urlApp_shor_short_p_cc879d_idx'),
        ),
    ]
